// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrSk5xhdZYsTiJUYEuqISH0t_0cLV5djE',
    appId: '1:71453756860:web:e0129c7bd92fd49741afb9',
    messagingSenderId: '71453756860',
    projectId: 'taskapp-c385f',
    authDomain: 'taskapp-c385f.firebaseapp.com',
    storageBucket: 'taskapp-c385f.firebasestorage.app',
    measurementId: 'G-ZVYVYKYQXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAGFyMApd0tX-X5zVh4qXQ45J1O2xS8Ro',
    appId: '1:71453756860:android:870003207931e78f41afb9',
    messagingSenderId: '71453756860',
    projectId: 'taskapp-c385f',
    storageBucket: 'taskapp-c385f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALNUaCGUnhZTea5RnUvNwrBY6FBHJ71ac',
    appId: '1:71453756860:ios:7c268fecbab410af41afb9',
    messagingSenderId: '71453756860',
    projectId: 'taskapp-c385f',
    storageBucket: 'taskapp-c385f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALNUaCGUnhZTea5RnUvNwrBY6FBHJ71ac',
    appId: '1:71453756860:ios:7c268fecbab410af41afb9',
    messagingSenderId: '71453756860',
    projectId: 'taskapp-c385f',
    storageBucket: 'taskapp-c385f.firebasestorage.app',
    iosBundleId: 'com.example.flutterFinal',
  );
}
